require:
 - rubocop-performance
 - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable

Style/Documentation:
  Enabled: false

Lint/MissingSuper:
  Exclude:
    - 'lib/**/**/*'

Metrics/MethodLength:
  Max: 1000

Metrics/ClassLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false